joinfaces:
  jsf:
    PROJECT_STAGE: Development
  primefaces:
    FONT_AWESOME: true
    theme: admin

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gl52?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC&useSSL=false
    username: gl52
    password: gl52
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate:
        enable_lazy_load_no_trans: true
  jmx:
      default-domain: gl52